### ISSUE TITLE
AWS us-west-1 availability zone count

### ISSUE THREAD

**Issue by danielsmithsd** [PatMyron/cloud#16]
This is a nuance which may or may not be helpful.  Feel free to close.

With regard to AWS' Availability Zone count in us-west-1, three is the correct documented count.  However, AWS only ever lets an account have two availability zones.  The third zone is virtually non-existent and similarly unusable.

**Comment by PatMyron** [comment]
(Sorry I missed this because of GitHub notification issues)

Some AWS accounts have access to more availability zones while newer AWS accounts can be restricted in congested regions like `us-west-1`, `sa-east-1`, `cn-north-1`

Unfortunately account-level differences are beyond the scope of this repo. This repo is mostly broad relative data to help newer cloud users make upfront architectural decisions like region selection and they'll discover the catches in their own time :)
